services:
  postgres:
    image: postgres:16
    container_name: passagens-postgres
    environment:
      POSTGRES_DB: passagens_search
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - passagens_pgdata:/var/lib/postgresql/data

volumes:
  passagens_pgdata: